on:
  push:
    branches: [main]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15-22.08
      options: --privileged
    steps:
    - uses: actions/checkout@v3
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
      with:
        bundle: nekoray.flatpak
        manifest-path: io.github.MatsuriDayo.nekoray.yaml
        cache-key: flatpak-builder-${{ github.sha }}
